### ISSUE TITLE
No module named 'gi'

### ISSUE THREAD

**Issue by Natetronn** [mendhak/grub-reboot-picker#3]
I'm getting the following error:

```
Traceback (most recent call last):
  File "/usr/bin/grub-reboot-picker", line 2, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
```
I'll see if I can install gi on my own for now.

**Comment by mendhak** [comment]
How are you running this?  If it's via the deb I've included `python3-gi` in the dependencies:

https://github.com/mendhak/grub-reboot-picker/blob/master/setup.cfg#L3

If it's directly via this repo you'll need to install the dependencies yourself:

https://github.com/mendhak/grub-reboot-picker#running-it-from-this-repo

**Comment by Natetronn** [comment]
Hi, thanks for the reply! I'm using the package from the AUR, which you can see the PKGBUILD for:

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=grub-reboot-picker

Looks like it's pulling the source (tar.gz)

**Comment by Natetronn** [comment]
I installed `PyGObject` with `python -m pip install PyGObject` and it now works. This particular AUR package looks like it's depends on python-goobject, which I see is in-fact installed.

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=grub-reboot-picker#n9

My guess is that version of PyGObject it isn't working because I'm using pyenv.

**Comment by yochananmarqos** [comment]
@Natetronn It's your issue, why don't you close it? :wink:
