### ISSUE TITLE
Make it available for 24.04

### ISSUE THREAD

**Issue by mendhak** [mendhak/grub-reboot-picker#6]
@mendhak hi, do you have any plans to make it available for 24.04 as well? I'm using Ubuntu 24.04 and currently running `sudo add-apt-repository ppa:mendhak/ppa` will complain that the repository does not have a release file. Hope this is added soon, and thank you for the great tool!

_Originally posted by @truonghm in https://github.com/mendhak/grub-reboot-picker/issues/5#issuecomment-2265737213_

**Comment by mendhak** [comment]
Oops I forgot, I usually use LTS quite late. I'll try to find some time to do this this weekend. @truonghm

**Comment by mendhak** [comment]
@truonghm if possible could you share your `sudo cat /boot/grub/grub.cfg` here. I'm only testing in a VM right now which is quite a limited grub.cfg

**Comment by truonghm** [comment]
@mendhak 
Hi, you can find the content of my `/boot/grub/grub.cfg` here: https://gist.github.com/truonghm/41d066e61a024f08687f82aca8881be8

**Comment by mendhak** [comment]
Thanks @truonghm I used that to test, it was useful.   
I've pushed a version 0.0.9 to the PPA so you should be able to see it now.   

![image](https://github.com/user-attachments/assets/2cac6450-f680-4601-a777-9c4fa690c1bc)
